<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Draco.Dap" Version="0.4.10-pre" />
    <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="4.0.726401" />
  </ItemGroup>

</Project>
